#server:
#  port: 9090

path.name: /

spring:
  application:
    name: h2-DB

  datasource:
    url: jdbc:h2:mem:h2db;Mode=Oracle
    platform: h2
    enable: true
    path: h2-console

#access h2: localhost:9090/h2-console
  #url: jdbc:h2:mem:h2db
  #add devtool dependency to pom
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update